// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: insert_mails.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMail = `-- name: InsertMail :one
INSERT INTO mails (
    -- COLUMS --
    created_at, --
    mail_provider, --
    mail_from, --
    success, --
    recipients, --
    subject, --
    content, --
    error --
)
    VALUES (
        -- VALUES --
        $1, --
        $2, --
        $3, --
        $4, --
        $5, --
        $6, --
        $7, --
        $8 --
)
RETURNING
    id
`

type InsertMailParams struct {
	CreatedAt    pgtype.Timestamp
	MailProvider string
	MailFrom     string
	Success      bool
	Recipients   []string
	Subject      string
	Content      string
	Error        pgtype.Text
}

func (q *Queries) InsertMail(ctx context.Context, arg InsertMailParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertMail,
		arg.CreatedAt,
		arg.MailProvider,
		arg.MailFrom,
		arg.Success,
		arg.Recipients,
		arg.Subject,
		arg.Content,
		arg.Error,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
