// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Mail struct {
	ID           int32
	CreatedAt    pgtype.Timestamp
	MailProvider string
	Success      bool
	// Encrypted sender email address
	MailFrom string
	// Encrypted array of recipient email addresses
	Recipients []string
	// Encrypted email subject
	Subject string
	// Encrypted email content
	Content string
	Error   pgtype.Text
}
