// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CountAllMails(ctx context.Context) (int64, error)
	FilterMailsOnCreatedAt(ctx context.Context, arg FilterMailsOnCreatedAtParams) ([]Mail, error)
	InsertMail(ctx context.Context, arg InsertMailParams) (int32, error)
	SelectAllMails(ctx context.Context, arg SelectAllMailsParams) ([]Mail, error)
	SelectMailByID(ctx context.Context, id int32) (Mail, error)
}

var _ Querier = (*Queries)(nil)
