// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: select_all_mails.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllMails = `-- name: CountAllMails :one
SELECT
    count(*)
FROM
    mails
`

func (q *Queries) CountAllMails(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllMails)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const filterMailsOnCreatedAt = `-- name: FilterMailsOnCreatedAt :many
SELECT
    id, created_at, mail_provider, success, mail_from, recipients, subject, content, error
FROM
    mails
WHERE
    created_at > $2
    AND created_at < $3
ORDER BY
    created_at DESC
LIMIT $1
`

type FilterMailsOnCreatedAtParams struct {
	Limit       int32
	CreatedAtLt pgtype.Timestamp
	CreatedAtGt pgtype.Timestamp
}

func (q *Queries) FilterMailsOnCreatedAt(ctx context.Context, arg FilterMailsOnCreatedAtParams) ([]Mail, error) {
	rows, err := q.db.Query(ctx, filterMailsOnCreatedAt, arg.Limit, arg.CreatedAtLt, arg.CreatedAtGt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mail
	for rows.Next() {
		var i Mail
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.MailProvider,
			&i.Success,
			&i.MailFrom,
			&i.Recipients,
			&i.Subject,
			&i.Content,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAllMails = `-- name: SelectAllMails :many
SELECT
    id, created_at, mail_provider, success, mail_from, recipients, subject, content, error
FROM
    mails
ORDER BY
    created_at DESC
LIMIT $1 offset $2
`

type SelectAllMailsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) SelectAllMails(ctx context.Context, arg SelectAllMailsParams) ([]Mail, error) {
	rows, err := q.db.Query(ctx, selectAllMails, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mail
	for rows.Next() {
		var i Mail
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.MailProvider,
			&i.Success,
			&i.MailFrom,
			&i.Recipients,
			&i.Subject,
			&i.Content,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
