// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: select_mail_by_id.sql

package db

import (
	"context"
)

const selectMailByID = `-- name: SelectMailByID :one
SELECT
    id, created_at, mail_provider, success, mail_from, recipients, subject, content, error
FROM
    mails
WHERE
    id = $1
`

func (q *Queries) SelectMailByID(ctx context.Context, id int32) (Mail, error) {
	row := q.db.QueryRow(ctx, selectMailByID, id)
	var i Mail
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.MailProvider,
		&i.Success,
		&i.MailFrom,
		&i.Recipients,
		&i.Subject,
		&i.Content,
		&i.Error,
	)
	return i, err
}
